# Generated by Django 4.1.3 on 2023-03-01 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_university_remove_otm_parent_category'),
        ('students', '0002_alter_studentwallet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentwallet',
            name='otm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.university'),
        ),
    ]
