# Generated by Django 4.1.3 on 2023-03-01 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentwallet_otm'),
        ('university', '0002_university_remove_otm_parent_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTM',
        ),
        migrations.AddField(
            model_name='university',
            name='parent_category',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'parent_category__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='university.university', verbose_name='Parent Category'),
        ),
    ]
