# Generated by Django 4.1.3 on 2023-03-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsorwallet',
            options={'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsors'},
        ),
        migrations.AddField(
            model_name='sponsorwallet',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sponsorwallet',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sponsorwallet',
            name='pay_type',
            field=models.CharField(blank=True, choices=[('Naqd', 'Naqd'), ('Pul o`tkazmasi', 'Pul o`tkazmasi')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorwallet',
            name='status',
            field=models.CharField(choices=[('Yangi', 'Yangi'), ('Moderatsiyada', 'Moderatsiyada'), ('Tasdiqlangan', 'Tasdiqlangan'), ('Bekor qilingan', 'Bekor qilingan')], default='Yangi', max_length=30),
        ),
    ]
